import {atom} from 'recoil'

export const postAtom = atom({
    key: 'postAtom',
    default: [
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
        {postImage: 'https://placehold.co/200'},
    ],
})
